### ISSUE TITLE
Unable to invoke no-args constructor for retrofit2.Call

### ISSUE THREAD

**Issue by zy888802** [gildor/kotlin-coroutines-retrofit#55]
**Version ： retrofit 2.6.2 
Json: GsonConverterFactory**

**When I use Call.awaitResponse() Call.await() hava error
but I use Call.enqueue()  Call.execute() no problem**

```
java.lang.RuntimeException: Unable to invoke no-args constructor for retrofit2.Call. Registering an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
 Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: retrofit2.Call
        at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) 
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

```

**Comment by gildor** [comment]
@zy888802 This error doesn't look related, could you provide some reproducible example of this behavior?

**Comment by erickok** [comment]
No; it looks like you try to deserialize some json into a `Call`. Perhaps you have a retrofit interface with a funtion that has return type of style `Call<Call<Something>>` instead of `Call<Something>`?

**Comment by zy888802** [comment]
This is what the crash log shows

This my code
```
 val okHttpClient = builder.build()
        retrofitClient = Retrofit.Builder().baseUrl(baseUrl)
            .addConverterFactory(GsonConverterFactory.create())
            .client(okHttpClient)
            .build()

 @POST("v1/verification-codes/{phone}")
    @Headers("Content-Type: application/json;charset=UTF-8")
    suspend fun getCode(@Path("phone") phone: String): BaseBean<String>
```

**Comment by erickok** [comment]
If you use this library you still need to define functions as non-suspend and a `Call<BaseBean<String>`. Are you instead looking for Retrofit 2.6's internal/official support, whoich allows you to directly define `suspend fun` in Retrofit interfaces?

**Comment by zy888802** [comment]
`suspend fun(..): Call<..>`
I delete suspend to solve the problem
Thank you very much！

**Comment by hamzaali6307** [comment]
i am also facing same issue . can you please suggest any possible solution for this.
